<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.BK3w42q' shared service.

return $this->privates['.service_locator.BK3w42q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CaisierController::FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::Compte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::add' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController::addUtilisateur' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UtilisateurController::updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CaisierController:FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:Compte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:add' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController:addUtilisateur' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UtilisateurController:updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
], [
    'App\\Controller\\CaisierController::FaireDepot' => '?',
    'App\\Controller\\PartenaireController::Compte' => '?',
    'App\\Controller\\PartenaireController::add' => '?',
    'App\\Controller\\PartenaireController::listParten' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\UtilisateurController::addUtilisateur' => '?',
    'App\\Controller\\UtilisateurController::updat' => '?',
    'App\\Controller\\CaisierController:FaireDepot' => '?',
    'App\\Controller\\PartenaireController:Compte' => '?',
    'App\\Controller\\PartenaireController:add' => '?',
    'App\\Controller\\PartenaireController:listParten' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\UtilisateurController:addUtilisateur' => '?',
    'App\\Controller\\UtilisateurController:updat' => '?',
]);
