<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.6MGCl6A' shared service.

return $this->privates['.service_locator.6MGCl6A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CaisierController::FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::add' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PartenaireController::listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController::register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\UtilisateurController::updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CaisierController:FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:add' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\PartenaireController:listParten' => ['privates', '.service_locator.eIEYWuf', 'get_ServiceLocator_EIEYWufService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController:register' => ['privates', '.service_locator.2B8PUum', 'get_ServiceLocator_2B8PUumService.php', true],
    'App\\Controller\\UtilisateurController:updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
], [
    'App\\Controller\\CaisierController::FaireDepot' => '?',
    'App\\Controller\\PartenaireController::add' => '?',
    'App\\Controller\\PartenaireController::listParten' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\UtilisateurController::register' => '?',
    'App\\Controller\\UtilisateurController::updat' => '?',
    'App\\Controller\\CaisierController:FaireDepot' => '?',
    'App\\Controller\\PartenaireController:add' => '?',
    'App\\Controller\\PartenaireController:listParten' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\UtilisateurController:register' => '?',
    'App\\Controller\\UtilisateurController:updat' => '?',
]);
