<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3PQP8gg\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3PQP8gg/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container3PQP8gg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container3PQP8gg\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container3PQP8gg\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '3PQP8gg',
    'container.build_id' => '26267157',
    'container.build_time' => 1565104968,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3PQP8gg');
