<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerV2hx2c2\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerV2hx2c2/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerV2hx2c2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerV2hx2c2\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerV2hx2c2\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'V2hx2c2',
    'container.build_id' => '6d724bb9',
    'container.build_time' => 1565016688,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerV2hx2c2');
