<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Y8.WdaJ' shared service.

return $this->privates['.service_locator.Y8.WdaJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CaisierController::FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::Compte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::add' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController::show' => ['privates', '.service_locator.WORG1MU', 'get_ServiceLocator_WORG1MUService.php', true],
    'App\\Controller\\PartenaireController::update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController::addUtilisateur' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UtilisateurController::alouerCompte' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\UtilisateurController::listuser' => ['privates', '.service_locator.pgfR0e.', 'get_ServiceLocator_PgfR0e_Service.php', true],
    'App\\Controller\\UtilisateurController::login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UtilisateurController::updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CaisierController:FaireDepot' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:Compte' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:add' => ['privates', '.service_locator.H3qnu8f', 'get_ServiceLocator_H3qnu8fService.php', true],
    'App\\Controller\\PartenaireController:show' => ['privates', '.service_locator.WORG1MU', 'get_ServiceLocator_WORG1MUService.php', true],
    'App\\Controller\\PartenaireController:update' => ['privates', '.service_locator..paYi0V', 'get_ServiceLocator__PaYi0VService.php', true],
    'App\\Controller\\UtilisateurController:addUtilisateur' => ['privates', '.service_locator..EwH3.j', 'get_ServiceLocator__EwH3_JService.php', true],
    'App\\Controller\\UtilisateurController:alouerCompte' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\UtilisateurController:listuser' => ['privates', '.service_locator.pgfR0e.', 'get_ServiceLocator_PgfR0e_Service.php', true],
    'App\\Controller\\UtilisateurController:login' => ['privates', '.service_locator.0xDS.HG', 'get_ServiceLocator_0xDS_HGService.php', true],
    'App\\Controller\\UtilisateurController:updat' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
], [
    'App\\Controller\\CaisierController::FaireDepot' => '?',
    'App\\Controller\\PartenaireController::Compte' => '?',
    'App\\Controller\\PartenaireController::add' => '?',
    'App\\Controller\\PartenaireController::show' => '?',
    'App\\Controller\\PartenaireController::update' => '?',
    'App\\Controller\\UtilisateurController::addUtilisateur' => '?',
    'App\\Controller\\UtilisateurController::alouerCompte' => '?',
    'App\\Controller\\UtilisateurController::listuser' => '?',
    'App\\Controller\\UtilisateurController::login' => '?',
    'App\\Controller\\UtilisateurController::updat' => '?',
    'App\\Controller\\CaisierController:FaireDepot' => '?',
    'App\\Controller\\PartenaireController:Compte' => '?',
    'App\\Controller\\PartenaireController:add' => '?',
    'App\\Controller\\PartenaireController:show' => '?',
    'App\\Controller\\PartenaireController:update' => '?',
    'App\\Controller\\UtilisateurController:addUtilisateur' => '?',
    'App\\Controller\\UtilisateurController:alouerCompte' => '?',
    'App\\Controller\\UtilisateurController:listuser' => '?',
    'App\\Controller\\UtilisateurController:login' => '?',
    'App\\Controller\\UtilisateurController:updat' => '?',
]);
