<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.pgfR0e.' shared service.

return $this->privates['.service_locator.pgfR0e.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'partenRepository' => ['privates', 'App\\Repository\\UtilisateurRepository', 'getUtilisateurRepositoryService.php', true],
    'serializer' => ['services', 'serializer', 'getSerializerService', false],
], [
    'partenRepository' => 'App\\Repository\\UtilisateurRepository',
    'serializer' => '?',
]);
