<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM7Hu7Ht\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM7Hu7Ht/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM7Hu7Ht.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM7Hu7Ht\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM7Hu7Ht\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M7Hu7Ht',
    'container.build_id' => '46948a3a',
    'container.build_time' => 1567514188,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM7Hu7Ht');
