<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTWX2148\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTWX2148/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTWX2148.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTWX2148\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerTWX2148\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'TWX2148',
    'container.build_id' => '5ca38085',
    'container.build_time' => 1566835639,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTWX2148');
