<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3yK1W4M\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3yK1W4M/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container3yK1W4M.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container3yK1W4M\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container3yK1W4M\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '3yK1W4M',
    'container.build_id' => 'cf7d5583',
    'container.build_time' => 1565037505,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3yK1W4M');
